Desktop/HW2_Django-main/articles/urls.py
from django.contrib import admin
from django.urls import path, include

from articles.apps import ArticlesConfig
from articles.views import ArticleCreateView, ArticleUpdateView, ArticleListView, ArticleDetailView, ArticleDeleteView, \
    article_is_publication

app_name = ArticlesConfig.name

urlpatterns = [
    path("create/", ArticleCreateView.as_view(), name="create"),
    path("", ArticleListView.as_view(), name="list"),
    path("view/<int:pk>/", ArticleDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", ArticleUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", ArticleDeleteView.as_view(), name="delete"),
    path("activity/<int:pk>/", article_is_publication, name="article_is_publication"),
]

Desktop/HW2_Django-main/catalog/urls.py
from django.contrib import admin
from django.urls import path, include

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, HomePageView, ContactsPageView

app_name = CatalogConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("products_list/", ProductListView.as_view(), name="products_list"),
    path("catalog/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
]

Desktop/HW2_Django-main/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("articles/", include("articles.urls", namespace="articles")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/HW2_Django-main/articles/models.py
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name="Заголовок",
        help_text="Введите заголовок статьи"
    )
    slug = models.CharField(
        max_length=150,
        verbose_name="Индефикатор",
        unique=True,
    )
    description = models.TextField(
        verbose_name="Статья",
        help_text="Введите текст статьи",
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        upload_to="articles/article/photo",
        blank=True,
        null=True,
        verbose_name="Фото",
        help_text="Загрузите превью статьи",
    )
    created_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата написания статьи",
        help_text="Укажите дату написания статьи",
    )
    is_publication = models.BooleanField(verbose_name="Опубликовать?", default=True)
    count_views = models.IntegerField(
        default=0,
        verbose_name="Количество просмотров статьи",
    )

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('articles:view', args=[self.pk])

Desktop/HW2_Django-main/catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Категория",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Наименование",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        upload_to="product/photo",
        blank=True,
        null=True,
        verbose_name="Фото",
        help_text="Загрузите фото продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите категорию продукта",
        blank=True,
        null=True,
        related_name='products',
    )
    price = models.IntegerField(
        default=0,
        verbose_name="Цена продукта",
        help_text="Введите цену продукта",
    )
    # manufactured_at = models.DateField(
    #     blank=True,
    #     null=True,
    #     verbose_name="Дата производства продукта",
    #     help_text="Укажите дату производства продукта",
    # )
    created_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата создания продукта",
        help_text="Укажите дату создания продукта",
    )
    updated_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата последнего изменения продукта",
        help_text="Укажите дату последнего изменения продукта",
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["category", "name"]

    def __str__(self):
        return self.name

Desktop/HW2_Django-main/articles/views.py
from django.urls.base import reverse
from django.utils.text import slugify
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from articles.models import Article


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'description', 'photo', 'created_at', 'is_publication')
    success_url = reverse_lazy('articles:list')

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articles:view', args=[self.object.pk])


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'description', 'photo', 'created_at', 'is_publication')
    success_url = reverse_lazy('articles:list')

    def get_success_url(self):
        # return reverse('articles:view', args=[self.object.pk])
        return self.object.get_absolute_url()


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        return Article.objects.filter(is_publication=True)


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('articles:list')


def article_is_publication(request, pk):
    article_item = get_object_or_404(Article, pk=pk)
    if article_item.is_publication:
        article_item.is_publication = False
    else:
        article_item.is_publication = True

    article_item.save()

    return redirect(reverse('articles:list'))

Desktop/HW2_Django-main/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView

from catalog.models import Product


class HomePageView(TemplateView):
    template_name = "catalog/home.html"


# def home(requests):
#     return render(requests, "catalog/home.html")


class ProductListView(ListView):
    model = Product

# def products_list(requests):
#     products = Product.objects.all()
#     context = {'products': products}
#     return render(requests, "product_list.html", context)


class ProductDetailView(DetailView):
    model = Product


# def product_detail(requests, pk):
#     product = get_object_or_404(Product, pk=pk)
#     context = {'product': product}
#     return render(requests, "product_detail.html", context)


class ContactsPageView(TemplateView):
    template_name = "catalog/contacts.html"


# def contacts(requests):
#     return render(requests, "catalog/contacts.html")

Desktop/HW2_Django-main/articles/templates/articles/article_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-12">
            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить статью "{{ object.title }}"?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a class="btn btn-primary" href="{% url 'articles:list' %}" role="button">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Desktop/HW2_Django-main/articles/templates/articles/article_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{{ object.photo | media_filter }}">
                    <p class="text-start">{{ object.description }}</p>
                    <a class="btn btn-primary" href="{% url 'articles:list'%}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Desktop/HW2_Django-main/articles/templates/articles/article_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-12">
            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                    Сохранить
                                    {% else %}
                                    Создать
                                    {% endif %}
                                </button>
                                <a class="btn btn-primary" href="{% url 'articles:list' %}" role="button">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Desktop/HW2_Django-main/articles/templates/articles/article_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <a class="p-2 btn btn-outline-primary" href="{% url 'articles:create' %}">Создать статью</a>
        <div class="pb-4"></div>
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{{ object.photo | media_filter }}" width="300" height="200">
                    <p class="text-start">{{ object.description | slice:100 }}</p>
                    <h1 class="card-title pricing-card-title"></h1>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'articles:view' object.id %}"
                               role="button">Подробно</a>
                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'articles:edit' object.id %}"
                               role="button">Изменить</a>
                            <a class="btn btn-sm btn-outline-danger" href="{% url 'articles:delete' object.id %}"
                               role="button">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Desktop/HW2_Django-main/catalog/templates/catalog/contacts.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <h1 class="display-4">Контакты</h1>
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>7708503727</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>г. Москва, ул Новая Басманная, д. 2/1, стр. 1</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Desktop/HW2_Django-main/catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/nav_bar.html' %}
<div class="pricing-header px-3 py-3 pt-md-2 pb-md-2 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - удобный онлайн-магазин</p>
</div>
{% block content %}
{% endblock %}
<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

Desktop/HW2_Django-main/catalog/templates/catalog/includes/nav_bar.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="ms-5">
        <a class="p-2 btn btn-dark btn-lg" href="{% url 'catalog:home' %}">Skystore</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products_list' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'articles:list' %}">Статьи</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>

Desktop/HW2_Django-main/catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <p class="text-start">{{ object.description }}</p>
                    <img src="{{ product.photo | media_filter }}" class="rounded mx-auto d-block" width="300" height="200">
                    <h1 class="card-title pricing-card-title">{{ object.price }} RUB </h1>
                    <a class="btn btn-primary" href="#" role="button">Купить</a>
                    <a class="btn btn-primary" href="{% url 'catalog:products_list'%}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Desktop/HW2_Django-main/catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {%  for product in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <p class="text-start">{{ product.description | slice:100 }}</p>
                    <img class="card-img-top" src="{{ product.photo | media_filter }}" width="300" height="200">
                    <h1 class="card-title pricing-card-title"></h1>
                    <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробно</a>
                </div>
            </div>
        </div>
        {%  endfor %}
    </div>
</div>
{% endblock %}